# Generated by Django 4.2.4 on 2023-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desv_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateform',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
