# Generated by Django 4.2.4 on 2023-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desv_form', '0002_evaluateform_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateform',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='evaluateform',
            name='education_level',
            field=models.CharField(max_length=100, null=True, verbose_name='Education Level'),
        ),
        migrations.AddField(
            model_name='evaluateform',
            name='employment_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='evaluateform',
            name='industry_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Industry Type'),
        ),
        migrations.AddField(
            model_name='evaluateform',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Income'),
        ),
        migrations.AddField(
            model_name='evaluateform',
            name='nationality',
            field=models.CharField(max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='evaluateform',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='evaluateform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='evaluateform',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='evaluateform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
